### ISSUE TITLE
Browser related actions on the Help menu for Linux doesn't work

### ISSUE THREAD

**Issue by clmartineau** [UnitexGramLab/gramlab-ide#125]
A detailed summary of the issue goes here. 

**What steps will reproduce the problem?**

  1. On both IDE, Help Menu: Website, Forum, Manuals (fr and en) don't work on Linux (KUbuntu 16.04 and 18.04)
  2. It works normally on Windows
  3. _____

**What is the expected output?**

[This could be a description, screenshot or any other output]

**What do you see instead?**

[This could be a description, screenshot or any other output]

**More info**

- Unitex/GramLab IDE version: #.#.# 
- UnitexToolLogger version: #.#.# 
- Did this work before?: [ ] yes [ ] no
- Forum thread:
- Log file (.ulp):

**Comment by martinec** [comment]
This seems to be related to a Kubuntu bug reported [here](https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1574879). I will look for a workaround.

**Comment by martinec** [comment]
Can you confirm if with [Unitex.jar.zip](https://github.com/UnitexGramLab/gramlab-ide/files/2953185/Unitex.jar.zip) the issue is fixed ?

**Comment by clmartineau** [comment]
It works for website and forum.
It doesn't work for manuals

**Comment by martinec** [comment]
@clmartineau What about now using [Unitex.jar.zip](https://github.com/UnitexGramLab/gramlab-ide/files/2953494/Unitex.jar.zip) in both Linux and Windows ?

**Comment by clmartineau** [comment]
Now all related actions on the Help menu work normally on both Linux and Windows.
Nonetheless on both systems on the Info menu, with  the "About Unitex" action you get now a java exception with the following message:
java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer;
at fr.umlv.unitex.text.TextAsListModelImpl.getElementAt(Unknown Source)
at fr.umlv.unitex.text.BigTextArea.refresh(Unknown Source)
at fr.umlv.unitex.text.BigTextArea$3.adjustmentValueChanged(Unknown Source)
at javax.swing.JScrollBar.fireAdjustmentValueChanged(JScrollBar.java:705)
at javax.swing.JScrollBar.access$100(JScrollBar.java:81)
at javax.swing.JScrollBar$ModelListener.stateChanged(JScrollBar.java:727)
at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
at javax.swing.DefaultBoundedRangeModel.setMaximum(DefaultBoundedRangeModel.java:219)
at javax.swing.JScrollBar.setMaximum(JScrollBar.java:563)
at fr.umlv.unitex.text.BigTextArea$2.intervalAdded(Unknown Source)
at javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:148)
at fr.umlv.unitex.text.TextAsListModelImpl.access$100(Unknown Source)
at fr.umlv.unitex.text.TextAsListModelImpl$1.process(Unknown Source)
at javax.swing.SwingWorker$3.run(SwingWorker.java:414)
at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
at javax.swing.Timer.fireActionPerformed(Timer.java:313)
at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by martinec** [comment]
> Now all related actions on the Help menu work normally on both Linux and Windows.

Great !

> Nonetheless on both systems on the Info menu, with the "About Unitex" action you get now a java exception with the following message:
> java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.position(I)Ljava/nio/MappedByteBuffer;

This is unrelated with the current issue.
